print("hello world \"astha\" here") 
print("line A\nline B")
print ("line A\tline B")
print("This is backslash/")
print("this is backslash\\")
print("this is backslash/")
print("This is backlash /")
print("There is hope in ever\brything")